{
    'name': 'Report Template Invoice',
    'category': 'Accounting & Finance',
    'author': 'Sternemedia',
    'website': 'www.sternemedia.com',
    'version': '1.0',
    'depends': [
    'sale','account','product_brand'
    ],
    'description': """
    """,
    'active': False,
    'update_xml': [],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/res_currency_data.xml',
        'views/res_currency.xml',
        'views/res_company.xml',
        'views/invoice_view.xml',
        'views/order_view.xml',
        'views/report_invoice.xml',
        'views/report_purchase.xml',
        'views/report_quotation.xml',
        'views/report_delivery.xml',
        'views/report_payment.xml',
        'views/report_picking_list.xml',
        'views/account_voucher_view.xml',
        'views/cai_view.xml',
        'views/ir_sequence_view.xml',
        'report.xml',
        'report_purchase.xml',
        'report_quotation.xml',
        'report_delivery.xml', 
        'report_payment.xml',
        'report_picking_list.xml',        
	],
    'images': ['static/description/main_screenshot.png'],
    'auto_install': False,
    'installable': True,
    'application': False,
}
